# Remove these ignores when actionlint supports self-repository references:
# https://github.com/rhysd/actionlint/issues/711
paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      - reusable workflow call "\$/.+" at "uses" is not following the format
      - specifying action "\$/.+" in invalid format because ref is missing
