# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# Enable only CSharpier for .NET formatting
ENABLE_LINTERS:
  - CSHARP_CSHARPIER

# Apply fixes automatically
APPLY_FIXES: all

SHOW_ELAPSED_TIME: true

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
