default_stages: [pre-commit]

repos:
  - repo: https://github.com/oxsecurity/megalinter
    rev: v8.7.0
    hooks:
      - id: megalinter-incremental # Faster, less thorough
        stages:
          - pre-commit
      - id: megalinter-full # Slower, more thorough
        stages:
          - pre-push
