name: recyclarr

networks:
  recyclarr:
    name: recyclarr_dev
    external: true

services:
  app:
    image: ghcr.io/recyclarr/recyclarr:edge
    user: $DOCKER_UID:$DOCKER_GID
    container_name: recyclarr
    build:
      context: .
      args:
        - TARGETARCH=amd64
    networks: [recyclarr]
    volumes:
      - ./docker/config:/config
    environment:
      CRON_SCHEDULE: "* * * * *"
      TZ: America/Chicago
