<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Recyclarr.Server\Recyclarr.Server.csproj" />
    <ProjectReference Include="..\Recyclarr.Core.TestLibrary\Recyclarr.Core.TestLibrary.csproj" />
    <ProjectReference Include="..\Recyclarr.TestLibrary\Recyclarr.TestLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.TestingHelpers" />
  </ItemGroup>
</Project>
