# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Setup GitVersion
description: Install GitVersion and determine version information
author: Recyclarr

outputs:
  preReleaseTag:
    description: The PreReleaseTag value
    value: ${{ steps.gitversion.outputs.preReleaseTag }}
  semVer:
    description: The SemVer value
    value: ${{ steps.gitversion.outputs.semVer }}

runs:
  using: composite
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@63daa16d3d7f45b16ad39d810aa8addf95785067 # v4.4.1
      with:
        # renovate: datasource=github-tags depName=GitTools/GitVersion
        versionSpec: 6.6.0

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@63daa16d3d7f45b16ad39d810aa8addf95785067 # v4.4.1
      id: gitversion
