# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Setup GitVersion
description: Install GitVersion and determine version information
author: Recyclarr

outputs:
  preReleaseTag:
    description: The PreReleaseTag value
    value: ${{ steps.gitversion.outputs.preReleaseTag }}
  semVer:
    description: The SemVer value
    value: ${{ steps.gitversion.outputs.semVer }}

runs:
  using: composite
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@5e921e851881443c3f3ae9108d9fb33f528f13d5 # v4.3.0
      with:
        # renovate: datasource=github-tags depName=GitTools/GitVersion
        versionSpec: 6.4.0

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@5e921e851881443c3f3ae9108d9fb33f528f13d5 # v4.3.0
      id: gitversion
