# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Setup GitVersion
description: Install GitVersion and determine version information
author: Recyclarr

outputs:
  preReleaseTag:
    description: The PreReleaseTag value
    value: ${{ steps.gitversion.outputs.preReleaseTag }}
  semVer:
    description: The SemVer value
    value: ${{ steps.gitversion.outputs.semVer }}

runs:
  using: composite
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@e0d584e657c606912e8fd522aeed29025975705f # v4.4.2
      with:
        # renovate: datasource=github-tags depName=GitTools/GitVersion
        versionSpec: 6.6.0

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@e0d584e657c606912e8fd522aeed29025975705f # v4.4.2
      id: gitversion
