[env]
RECYCLARR_CONFIG_DIR = "{{config_root ~ '/../dev-configs/appdata' | canonicalize}}"

[tools]
"github:santhosh-tekuri/jsonschema" = "latest"
"npm:@microsoft/learn-cli" = "latest"
python = "latest"
wrangler = "latest"
