name: Setup .NET SDK & Tools
description: Setup .NET SDK and restore dotnet tools for GitHub Actions
runs:
  using: composite
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
      with:
        dotnet-version: 9.0.x
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_NOLOGO: 1
    
    - name: Restore dotnet tools
      shell: bash
      run: dotnet tool restore
