# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Schemas

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

env:
  DEPLOY_BRANCH: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || 'master' }}

jobs:
  deploy:
    name: Deploy Schemas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build schemas
        run: ./ci/build-schemas.py

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy schemas-dist --project-name=recyclarr-schemas --branch=${{ env.DEPLOY_BRANCH }}
