name: Update Sponsors
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [master]
    paths:
      - .github/workflows/sponsors.yml

permissions:
  contents: write

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.RECYCLARR_APP_ID }}
          private-key: ${{ secrets.RECYCLARR_PRIVATE_KEY }}
          permission-contents: write

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@2fd9142e765f755780202122261dc85e78459405 # v1.6.0
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: README.md
          active-only: false

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "chore: update sponsors in README"
